version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: "db"
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=abc
      - MYSQL_DATABASE=chatter
    ports:
      - 3307:3306
    volumes:
      - ./my-db:/var/lib/mysql
  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:3306/chatter",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "abc",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    depends_on:
      - db
    volumes:
      - .m2:/root/.m2
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./frontend/:/frontend/
      - node_modules:/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    restart: unless-stopped
    volumes:
      - ./frontend/:/frontend/
      - client_node_modules:/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  my-db:
  node_modules:
  client_node_modules: